version: '3.3'
services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - app:/usr/src/app
    networks:
      - backend
volumes:
  app:

networks:
  backend:
    driver: bridge
